# syntax=docker/dockerfile:1
  #FROM mcr.microsoft.com/dotnet/aspnet:6.0-bullseye-slim
  FROM mcr.microsoft.com/dotnet/aspnet:6.0
  
  COPY publish/ app/
  WORKDIR /app
  ENTRYPOINT ["dotnet", "Sample.dll"]