# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: NET 6 Build

env:
  APPSERVICE_NAME: lztk-demo-sample
  ARTIFACT_NAME: sample-dotnet-app
  PROJECT_PATH: './azure-settings/Sample/Sample.csproj'
  DOTNET_VERSION: '6.0.x'
  CONFIGURATION: Release

on:
  push:
    branches: [ main ] # Trigger build on pushes to main
  workflow_dispatch:   # Allows to manually trigger builds

jobs:
  build:
    name: Build & Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
           fetch-depth: '1'

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '${{ env.DOTNET_VERSION }}'
          include-prerelease: true

      - name: Install dependencies
        run: dotnet restore '${{ env.PROJECT_PATH }}'

      - name: Build with dotnet
        run: dotnet build '${{env.PROJECT_PATH}}' --configuration ${{ env.CONFIGURATION }}

      - name: dotnet publish
        run: dotnet publish '${{env.PROJECT_PATH}}' --no-build -c ${{ env.CONFIGURATION }} -o ${{env.DOTNET_ROOT}}/app

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{env.DOTNET_ROOT}}/app

  deploy:
    name: Deploy to App Service
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APPSERVICE_NAME }}
          publish-profile: ${{ secrets.APPSERVICE_SAMPLE_DEMO }}
          package: .